Traceback (most recent call last):
  File "C:\Users\Pooja Vinod\anaconda3\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\Pooja Vinod\anaconda3\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pooja Vinod\anaconda3\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pooja Vinod\anaconda3\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Pooja Vinod\anaconda3\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Pooja Vinod\anaconda3\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Pooja Vinod\anaconda3\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#!pip install pydantic-settings
#!pip install --upgrade pandas-profiling
#!pip install pandas_profiling==3.2.0 pydantic==1.10.2
#!pip uninstall -y pandas-profiling
# !pip install ydata-profiling
#!pip install -U pandas-profiling
%load_ext sql
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 7[0m
[0;32m      1[0m [38;5;66;03m#!pip install pydantic-settings[39;00m
[0;32m      2[0m [38;5;66;03m#!pip install --upgrade pandas-profiling[39;00m
[0;32m      3[0m [38;5;66;03m#!pip install pandas_profiling==3.2.0 pydantic==1.10.2[39;00m
[0;32m      4[0m [38;5;66;03m#!pip uninstall -y pandas-profiling[39;00m
[0;32m      5[0m [38;5;66;03m# !pip install ydata-profiling[39;00m
[0;32m      6[0m [38;5;66;03m#!pip install -U pandas-profiling[39;00m
[1;32m----> 7[0m get_ipython()[38;5;241m.[39mrun_line_magic([38;5;124m'[39m[38;5;124mload_ext[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124msql[39m[38;5;124m'[39m)

File [1;32m~\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:2480[0m, in [0;36mInteractiveShell.run_line_magic[1;34m(self, magic_name, line, _stack_depth)[0m
[0;32m   2478[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[0;32m   2479[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[1;32m-> 2480[0m     result [38;5;241m=[39m fn([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m   2482[0m [38;5;66;03m# The code below prevents the output from being displayed[39;00m
[0;32m   2483[0m [38;5;66;03m# when using magics with decorator @output_can_be_silenced[39;00m
[0;32m   2484[0m [38;5;66;03m# when the last Python token in the expression is a ';'.[39;00m
[0;32m   2485[0m [38;5;28;01mif[39;00m [38;5;28mgetattr[39m(fn, magic[38;5;241m.[39mMAGIC_OUTPUT_CAN_BE_SILENCED, [38;5;28;01mFalse[39;00m):

File [1;32m~\anaconda3\Lib\site-packages\IPython\core\magics\extension.py:33[0m, in [0;36mExtensionMagics.load_ext[1;34m(self, module_str)[0m
[0;32m     31[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m module_str:
[0;32m     32[0m     [38;5;28;01mraise[39;00m UsageError([38;5;124m'[39m[38;5;124mMissing module name.[39m[38;5;124m'[39m)
[1;32m---> 33[0m res [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39mextension_manager[38;5;241m.[39mload_extension(module_str)
[0;32m     35[0m [38;5;28;01mif[39;00m res [38;5;241m==[39m [38;5;124m'[39m[38;5;124malready loaded[39m[38;5;124m'[39m:
[0;32m     36[0m     [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mThe [39m[38;5;132;01m%s[39;00m[38;5;124m extension is already loaded. To reload it, use:[39m[38;5;124m"[39m [38;5;241m%[39m module_str)

File [1;32m~\anaconda3\Lib\site-packages\IPython\core\extensions.py:62[0m, in [0;36mExtensionManager.load_extension[1;34m(self, module_str)[0m
[0;32m     55[0m [38;5;250m[39m[38;5;124;03m"""Load an IPython extension by its module name.[39;00m
[0;32m     56[0m 
[0;32m     57[0m [38;5;124;03mReturns the string "already loaded" if the extension is already loaded,[39;00m
[0;32m     58[0m [38;5;124;03m"no load function" if the module doesn't have a load_ipython_extension[39;00m
[0;32m     59[0m [38;5;124;03mfunction, or None if it succeeded.[39;00m
[0;32m     60[0m [38;5;124;03m"""[39;00m
[0;32m     61[0m [38;5;28;01mtry[39;00m:
[1;32m---> 62[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_load_extension(module_str)
[0;32m     63[0m [38;5;28;01mexcept[39;00m [38;5;167;01mModuleNotFoundError[39;00m:
[0;32m     64[0m     [38;5;28;01mif[39;00m module_str [38;5;129;01min[39;00m BUILTINS_EXTS:

File [1;32m~\anaconda3\Lib\site-packages\IPython\core\extensions.py:77[0m, in [0;36mExtensionManager._load_extension[1;34m(self, module_str)[0m
[0;32m     75[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mshell[38;5;241m.[39mbuiltin_trap:
[0;32m     76[0m     [38;5;28;01mif[39;00m module_str [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m sys[38;5;241m.[39mmodules:
[1;32m---> 77[0m         mod [38;5;241m=[39m import_module(module_str)
[0;32m     78[0m     mod [38;5;241m=[39m sys[38;5;241m.[39mmodules[module_str]
[0;32m     79[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_call_load_ipython_extension(mod):

File [1;32m~\anaconda3\Lib\importlib\__init__.py:90[0m, in [0;36mimport_module[1;34m(name, package)[0m
[0;32m     88[0m             [38;5;28;01mbreak[39;00m
[0;32m     89[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[1;32m---> 90[0m [38;5;28;01mreturn[39;00m _bootstrap[38;5;241m.[39m_gcd_import(name[level:], package, level)

File [1;32m<frozen importlib._bootstrap>:1387[0m, in [0;36m_gcd_import[1;34m(name, package, level)[0m

File [1;32m<frozen importlib._bootstrap>:1360[0m, in [0;36m_find_and_load[1;34m(name, import_)[0m

File [1;32m<frozen importlib._bootstrap>:1324[0m, in [0;36m_find_and_load_unlocked[1;34m(name, import_)[0m

[1;31mModuleNotFoundError[0m: No module named 'sql'

